import type { CombatMove } from '../animations/types';

export const COMBAT_MOVES: Record<string, CombatMove> = {
  flyingPunch: {
    id: 'flyingPunch',
    context: 'AIR',
    animation: 'flyingPunch',
    startup: 0.10,
    active: 0.16,
    recovery: 0.18,
    cancelAt: 0.65,
    damage: 35000,
    radius: 1.8,
    impulse: 35,
    speedScaling: true,
    sizeScaling: true,
    targetAssist: true,
    boneMask: 'UPPER_BODY',
    events: [
      { time: 0.0, event: 'attack.start' },
      { time: 0.22, event: 'attack.activeStart' },
      { time: 0.42, event: 'attack.hit' },
      { time: 0.62, event: 'attack.activeEnd' },
      { time: 0.75, event: 'attack.cancelWindow' },
      { time: 1.0, event: 'attack.complete' },
    ],
  },
  kineticStrike: {
    id: 'kineticStrike',
    context: 'HIGH_SPEED_AIR',
    animation: 'kineticStrike',
    startup: 0.08,
    active: 0.20,
    recovery: 0.24,
    cancelAt: 0.70,
    damage: 120000,
    radius: 5.5,
    impulse: 90,
    speedScaling: true,
    sizeScaling: true,
    targetAssist: true,
    boneMask: 'UPPER_BODY',
    events: [
      { time: 0.0, event: 'attack.start' },
      { time: 0.18, event: 'attack.activeStart' },
      { time: 0.36, event: 'attack.hit' },
      { time: 0.60, event: 'attack.activeEnd' },
      { time: 0.75, event: 'attack.cancelWindow' },
      { time: 1.0, event: 'attack.complete' },
    ],
  },
  meteorPunch: {
    id: 'meteorPunch',
    context: 'AIR',
    animation: 'meteorPunch',
    startup: 0.15,
    active: 0.30,
    recovery: 0.25,
    cancelAt: 0.80,
    damage: 85000,
    radius: 4.2,
    impulse: 70,
    speedScaling: true,
    sizeScaling: true,
    targetAssist: true,
    boneMask: 'FULL_BODY',
    events: [
      { time: 0.0, event: 'attack.start' },
      { time: 0.25, event: 'attack.activeStart' },
      { time: 0.55, event: 'meteor.impact' },
      { time: 0.70, event: 'attack.activeEnd' },
      { time: 0.85, event: 'attack.cancelWindow' },
      { time: 1.0, event: 'attack.complete' },
    ],
  },
  flyingKick: {
    id: 'flyingKick',
    context: 'AIR',
    animation: 'flyingKick',
    startup: 0.12,
    active: 0.22,
    recovery: 0.24,
    cancelAt: 0.70,
    damage: 42000,
    radius: 2.2,
    impulse: 45,
    speedScaling: true,
    sizeScaling: true,
    targetAssist: true,
    boneMask: 'FULL_BODY',
    events: [
      { time: 0.0, event: 'attack.start' },
      { time: 0.25, event: 'attack.activeStart' },
      { time: 0.45, event: 'kick.hit' },
      { time: 0.65, event: 'attack.activeEnd' },
      { time: 0.80, event: 'attack.cancelWindow' },
      { time: 1.0, event: 'attack.complete' },
    ],
  },
  punch: {
    id: 'punch',
    context: 'GROUND',
    animation: 'punch',
    startup: 0.10,
    active: 0.15,
    recovery: 0.17,
    cancelAt: 0.65,
    damage: 30000,
    radius: 1.5,
    impulse: 25,
    speedScaling: true,
    sizeScaling: true,
    targetAssist: true,
    boneMask: 'UPPER_BODY',
    events: [
      { time: 0.0, event: 'attack.start' },
      { time: 0.25, event: 'attack.activeStart' },
      { time: 0.45, event: 'attack.hit' },
      { time: 0.65, event: 'attack.activeEnd' },
      { time: 0.80, event: 'attack.cancelWindow' },
      { time: 1.0, event: 'attack.complete' },
    ],
    nextMoves: ['punchCross'],
  },
  punchCross: {
    id: 'punchCross',
    context: 'GROUND',
    animation: 'punchCross',
    startup: 0.10,
    active: 0.15,
    recovery: 0.17,
    cancelAt: 0.65,
    damage: 35000,
    radius: 1.6,
    impulse: 30,
    speedScaling: true,
    sizeScaling: true,
    targetAssist: true,
    boneMask: 'UPPER_BODY',
    events: [
      { time: 0.0, event: 'attack.start' },
      { time: 0.25, event: 'attack.activeStart' },
      { time: 0.45, event: 'attack.hit' },
      { time: 0.65, event: 'attack.activeEnd' },
      { time: 0.80, event: 'attack.cancelWindow' },
      { time: 1.0, event: 'attack.complete' },
    ],
    nextMoves: ['punchUpper'],
  },
  punchUpper: {
    id: 'punchUpper',
    context: 'GROUND',
    animation: 'punchUpper',
    startup: 0.12,
    active: 0.18,
    recovery: 0.20,
    cancelAt: 0.70,
    damage: 48000,
    radius: 2.0,
    impulse: 40,
    speedScaling: true,
    sizeScaling: true,
    targetAssist: true,
    boneMask: 'UPPER_BODY',
    events: [
      { time: 0.0, event: 'attack.start' },
      { time: 0.30, event: 'attack.activeStart' },
      { time: 0.50, event: 'attack.hit' },
      { time: 0.70, event: 'attack.activeEnd' },
      { time: 0.85, event: 'attack.cancelWindow' },
      { time: 1.0, event: 'attack.complete' },
    ],
  },
  kick: {
    id: 'kick',
    context: 'GROUND',
    animation: 'kick',
    startup: 0.14,
    active: 0.20,
    recovery: 0.21,
    cancelAt: 0.70,
    damage: 38000,
    radius: 1.8,
    impulse: 32,
    speedScaling: true,
    sizeScaling: true,
    targetAssist: true,
    boneMask: 'FULL_BODY',
    events: [
      { time: 0.0, event: 'attack.start' },
      { time: 0.30, event: 'attack.activeStart' },
      { time: 0.50, event: 'kick.hit' },
      { time: 0.70, event: 'attack.activeEnd' },
      { time: 0.85, event: 'attack.cancelWindow' },
      { time: 1.0, event: 'attack.complete' },
    ],
    nextMoves: ['kickSide'],
  },
  kickSide: {
    id: 'kickSide',
    context: 'GROUND',
    animation: 'kickSide',
    startup: 0.15,
    active: 0.22,
    recovery: 0.23,
    cancelAt: 0.70,
    damage: 42000,
    radius: 2.0,
    impulse: 38,
    speedScaling: true,
    sizeScaling: true,
    targetAssist: true,
    boneMask: 'FULL_BODY',
    events: [
      { time: 0.0, event: 'attack.start' },
      { time: 0.30, event: 'attack.activeStart' },
      { time: 0.50, event: 'kick.hit' },
      { time: 0.70, event: 'attack.activeEnd' },
      { time: 0.85, event: 'attack.cancelWindow' },
      { time: 1.0, event: 'attack.complete' },
    ],
  },
};
