import type { ReferenceFrameGraph } from '../spatial/ReferenceFrameGraph';
import { cloneVec3, type Vec3, finite, lengthVec3 } from '../spatial/units';
import { referenceFrame } from '../spatial/ReferenceFrame';
import type { CelestialBody } from './CelestialBody';
import type { CelestialSystemRuntime, BodyHandoffState } from './CelestialSystemRuntime';
import type { ProceduralSystem } from './SystemGenerator';

/**
 * Radius of a body's ellipsoid toward a direction, from that direction's polar component:
 * `R = ab / sqrt((a sin)^2 + (b cos)^2)`.
 */
function directionalRadiusM(body: CelestialBody, sinLat: number): number {
  const a = body.equatorialRadiusM;
  const b = finite(body.polarRadiusM, a);
  if (a === b) return a;
  const cosLat = Math.sqrt(Math.max(0, 1 - sinLat * sinLat));
  return (a * b) / Math.sqrt((a * sinLat) ** 2 + (b * cosLat) ** 2);
}

export class ProceduralSystemRuntime implements CelestialSystemRuntime {
  private readonly states = new Map<string, { positionM: Vec3, velocityMps: Vec3 }>();
  private epochS: number = 0;
  public readonly bodies: readonly CelestialBody[];
  
  // Keep track of orbit radius and speeds
  // For a procedural system generated by SystemGenerator, we don't have Keplerian elements,
  // but we can generate them deterministically or use a simple circular orbit.
  private readonly orbits = new Map<string, { radius: number, speed: number, phase: number }>();

  constructor(public readonly system: ProceduralSystem, epochS: number = 0) {
    this.bodies = system.bodies;
    
    // Compute simple circular orbits for planets and moons.
    // The generator produces bodies in order: Star -> Planet -> Moons -> Planet -> Moons
    let currentOrbitM = 5e10; 
    let currentPlanetOrbitM = 0;
    
    // Simple deterministic PRNG based on seed to assign orbit phases
    let state = system.seed || 0x9e37_79b9_7f4a_7c15n;
    const nextFloat = () => {
      state ^= (state << 13n) & 0xffff_ffff_ffff_ffffn;
      state ^= state >> 7n;
      state ^= (state << 17n) & 0xffff_ffff_ffff_ffffn;
      state &= 0xffff_ffff_ffff_ffffn;
      return Number(state >> 11n) / 2 ** 53;
    };

    for (const body of this.bodies) {
      if (!body.parentId || body.parentId === system.starId) {
        if (body.id === system.starId) {
          this.orbits.set(body.id, { radius: 0, speed: 0, phase: 0 });
        } else {
          // It's a planet
          const radiusM = currentOrbitM + nextFloat() * 1.5e11 + 2e10;
          currentPlanetOrbitM = radiusM;
          currentOrbitM = radiusM;
          // approximate orbital speed v = sqrt(GM/r)
          const G = 6.67430e-11;
          const M = this.bodies[0]?.massKg ?? 1.989e30;
          const speed = Math.sqrt((G * M) / radiusM);
          this.orbits.set(body.id, { radius: radiusM, speed: speed / radiusM, phase: nextFloat() * Math.PI * 2 });
        }
      } else {
        // It's a moon
        const radiusM = body.equatorialRadiusM * (3 + nextFloat() * 5); // simple moon distance
        const G = 6.67430e-11;
        const parent = this.bodies.find(b => b.id === body.parentId);
        const M = parent?.massKg ?? 1e24;
        const speed = Math.sqrt((G * M) / radiusM);
        this.orbits.set(body.id, { radius: radiusM, speed: speed / radiusM, phase: nextFloat() * Math.PI * 2 });
      }
    }

    this.update(epochS);
  }

  get time(): number { return this.epochS; }

  update(epochS: number): void {
    this.epochS = finite(epochS);
    this.states.clear();
    for (const body of this.bodies) this.resolve(body);
  }

  private resolve(body: CelestialBody): { positionM: Vec3, velocityMps: Vec3 } {
    const cached = this.states.get(body.id);
    if (cached) return cached;

    const orbit = this.orbits.get(body.id) ?? { radius: 0, speed: 0, phase: 0 };
    const angle = orbit.phase + orbit.speed * this.epochS;
    
    let localPos: Vec3 = [Math.cos(angle) * orbit.radius, 0, Math.sin(angle) * orbit.radius];
    let localVel: Vec3 = [-Math.sin(angle) * orbit.speed * orbit.radius, 0, Math.cos(angle) * orbit.speed * orbit.radius];

    if (body.parentId && body.parentId !== this.system.starId) {
      const parent = this.bodies.find(b => b.id === body.parentId);
      if (parent) {
        const pState = this.resolve(parent);
        localPos = [localPos[0] + pState.positionM[0], localPos[1] + pState.positionM[1], localPos[2] + pState.positionM[2]];
        localVel = [localVel[0] + pState.velocityMps[0], localVel[1] + pState.velocityMps[1], localVel[2] + pState.velocityMps[2]];
      }
    }

    const state = { positionM: localPos, velocityMps: localVel };
    this.states.set(body.id, state);
    return state;
  }

  positionOf(bodyId: string): Vec3 | undefined {
    return this.states.get(bodyId)?.positionM;
  }

  dominantBody(observerM: Vec3): CelestialBody | undefined {
    // Determine the closest body by surface distance
    let closest: CelestialBody | undefined;
    let minDistance = Infinity;
    for (const body of this.bodies) {
      const state = this.states.get(body.id);
      if (!state) continue;
      const dx = observerM[0] - state.positionM[0];
      const dy = observerM[1] - state.positionM[1];
      const dz = observerM[2] - state.positionM[2];
      const distance = Math.hypot(dx, dy, dz);
      if (distance < minDistance) {
        minDistance = distance;
        closest = body;
      }
    }
    return closest;
  }

  handoff(bodyId: string, observerM: Vec3): BodyHandoffState | undefined {
    const state = this.states.get(bodyId);
    if (!state) return undefined;
    const body = this.bodies.find(b => b.id === bodyId);
    if (!body) return undefined;

    const dx = observerM[0] - state.positionM[0];
    const dy = observerM[1] - state.positionM[1];
    const dz = observerM[2] - state.positionM[2];
    const distance = Math.max(1, Math.hypot(dx, dy, dz));
    const radius = directionalRadiusM(body, dz / distance);
    const angularRadius = distance <= radius ? Math.PI / 2 : Math.asin(Math.min(1, radius / distance));
    const surfaceDistance = distance - radius;

    const celestialLimit = 0.001;
    const surfaceLimit = 0.35;
    const mode = angularRadius < celestialLimit ? 'celestial'
      : angularRadius < surfaceLimit ? 'planet' : 'surface';
    const blend = mode === 'celestial'
      ? Math.min(1, angularRadius / celestialLimit)
      : mode === 'planet'
        ? (angularRadius - celestialLimit) / (surfaceLimit - celestialLimit)
        : 1;

    return {
      bodyId, mode, blend: Math.min(1, Math.max(0, blend)),
      apparentAngularRadiusRad: angularRadius,
      distanceToSurfaceM: surfaceDistance,
    };
  }

  registerFrames(graph: ReferenceFrameGraph): void {
    const systemFrame = `system/${this.system.starId}`;
    if (!graph.has(systemFrame)) {
      graph.register(referenceFrame({ id: systemFrame, kind: 'system', label: `System ${this.system.starId}` }));
    }
    for (const body of this.bodies) {
      const state = this.states.get(body.id);
      graph.register(referenceFrame({
        id: body.frameId,
        parentId: systemFrame,
        kind: 'body-fixed',
        originInParent: state ? cloneVec3(state.positionM) : [0, 0, 0],
        label: body.name,
      }));
    }
  }

  speedOf(bodyId: string): number {
    const state = this.states.get(bodyId);
    return state ? lengthVec3(state.velocityMps) : Number.NaN;
  }
}
