import test from 'node:test';
import assert from 'node:assert/strict';
import { UniverseRuntime } from '../src/world/runtime/UniverseRuntime.ts';
import { RockyImpactDestructionService } from '../src/world/destruction/RockyImpactDestructionService.ts';
import { rockyEvent } from './helpers/rocky-impact.ts';
const u=new UniverseRuntime(),body=u.activeSystem.bodies.find(b=>b.id==='moon')!,e=rockyEvent(body),store=u.volume.edits;
let requests=0;const service=new RockyImpactDestructionService({edits:store,body:id=>u.activeSystem.bodies.find(b=>b.id===id),requestRegion:()=>requests++});
const id=service.consume(e)!;
test('T_D1_EVENT_CREATES_EXACTLY_ONE_EDIT',()=>assert.equal(store.editCount,1));
test('T_D1_DUPLICATE_EVENT_ID_NO_SECOND_EDIT',()=>{assert.equal(service.consume(e),id);assert.equal(store.editCount,1);assert.equal(store.revision(body.id),1);});
test('T_D1_EDIT_ID_DETERMINISTIC',()=>assert.equal(id,`moon:impact:${e.eventId}`));
test('T_D1_EDIT_BODY_ID_CORRECT',()=>assert.equal(store.get(id)!.bodyId,'moon'));
test('T_D1_EDIT_TYPE_SUBTRACT_SPHERE',()=>{assert.equal(store.get(id)!.type,'subtract-sphere');assert.ok(JSON.parse(JSON.stringify(store.get(id))).impact);});
test('T_D1_EDIT_REVISION_INCREMENTS',()=>assert.equal(store.revision(body.id),1));
test('T_D1_CATASTROPHIC_DOES_NOT_INCREMENT_EDIT_REVISION',()=>{service.consume(rockyEvent(body,299792458,'catastrophic'));assert.equal(store.revision(body.id),1);assert.equal(store.editCount,1);});
test('T_D1_EVENT_DOES_NOT_MUTATE_CELESTIAL_CATALOG',()=>{const before=JSON.stringify(u.activeSystem.bodies);service.consume(e);assert.equal(JSON.stringify(u.activeSystem.bodies),before);assert.ok(requests);});
test('manual lock alone remains eligible; assisted captures are ignored',()=>{assert.ok(service.consume({...e,eventId:'locked-manual',lockedTarget:true}));const count=store.editCount;
  service.consume({...e,eventId:'assisted',classification:'SAFE_CAPTURE',lockedTarget:true,autopilotActive:true});assert.equal(store.editCount,count);});
test('authored coverage defers explicitly without a competing edit',()=>{const deferred=new RockyImpactDestructionService({edits:store,body:()=>body,requestRegion:()=>{throw new Error('deferred demand');},defer:()=> 'authored-manaus-authority'});
  assert.equal(deferred.consume({...e,eventId:'deferred'}),undefined);assert.equal(deferred.last!.reason,'authored-manaus-authority');});
