export type BoneMap = Record<string, string>;

export const KAYKIT_MAP: BoneMap = {
  HIPS: 'hips',
  SPINE: 'spine',
  CHEST: 'chest',
  HEAD: 'head',
  LEFT_ARM: 'upperarm.l',
  LEFT_FOREARM: 'lowerarm.l',
  LEFT_HAND: 'hand.l',
  RIGHT_ARM: 'upperarm.r',
  RIGHT_FOREARM: 'lowerarm.r',
  RIGHT_HAND: 'hand.r',
  LEFT_LEG: 'upperleg.l',
  LEFT_SHIN: 'lowerleg.l',
  LEFT_FOOT: 'foot.l',
  RIGHT_LEG: 'upperleg.r',
  RIGHT_SHIN: 'lowerleg.r',
  RIGHT_FOOT: 'foot.r',
};

export const QUATERNIUS_MAP: BoneMap = {
  HIPS: 'pelvis',
  SPINE: 'spine_01',
  CHEST: 'spine_03',
  NECK: 'neck_01',
  HEAD: 'Head',
  LEFT_SHOULDER: 'clavicle_l',
  LEFT_ARM: 'upperarm_l',
  LEFT_FOREARM: 'lowerarm_l',
  LEFT_HAND: 'hand_l',
  RIGHT_SHOULDER: 'clavicle_r',
  RIGHT_ARM: 'upperarm_r',
  RIGHT_FOREARM: 'lowerarm_r',
  RIGHT_HAND: 'hand_r',
  LEFT_LEG: 'thigh_l',
  LEFT_SHIN: 'calf_l',
  LEFT_FOOT: 'foot_l',
  RIGHT_LEG: 'thigh_r',
  RIGHT_SHIN: 'calf_r',
  RIGHT_FOOT: 'foot_r',
};
